#!/bin/bash
mpirun -n 8 python biasvariance_vst.py 0
mpirun -n 8 python biasvariance_vst.py 1
mpirun -n 8 python biasvariance_vst.py 2
mpirun -n 8 python biasvariance_vst.py 3
mpirun -n 8 python biasvariance_vst.py 4
mpirun -n 8 python biasvariance_vst.py 5
mpirun -n 8 python biasvariance_vst.py 6
mpirun -n 8 python biasvariance_vst.py 7
mpirun -n 8 python biasvariance_vst.py 8
mpirun -n 8 python biasvariance_vst.py 9
mpirun -n 8 python biasvariance_vst.py 10
mpirun -n 8 python biasvariance_vst.py 11
mpirun -n 8 python biasvariance_vst.py 12
mpirun -n 8 python biasvariance_vst.py 13
mpirun -n 8 python biasvariance_vst.py 14
mpirun -n 8 python biasvariance_vst.py 15
mpirun -n 8 python biasvariance_vst.py 16
mpirun -n 8 python biasvariance_vst.py 17
mpirun -n 8 python biasvariance_vst.py 18
mpirun -n 8 python biasvariance_vst.py 19
mpirun -n 8 python biasvariance_vst.py 20
mpirun -n 8 python biasvariance_vst.py 21
mpirun -n 8 python biasvariance_vst.py 22
mpirun -n 8 python biasvariance_vst.py 23
mpirun -n 8 python biasvariance_vst.py 24
mpirun -n 8 python biasvariance_vst.py 25
mpirun -n 8 python biasvariance_vst.py 26
mpirun -n 8 python biasvariance_vst.py 27
mpirun -n 8 python biasvariance_vst.py 28
mpirun -n 8 python biasvariance_vst.py 29 
mpirun -n 8 python biasvariance_vst.py 30
mpirun -n 8 python biasvariance_vst.py 31
mpirun -n 8 python biasvariance_vst.py 32
mpirun -n 8 python biasvariance_vst.py 33
mpirun -n 8 python biasvariance_vst.py 34
