#!/bin/bash
mpirun -n 8 python biasvariance_vst_all.py 0
mpirun -n 8 python biasvariance_vst_all.py 1
mpirun -n 8 python biasvariance_vst_all.py 2
mpirun -n 8 python biasvariance_vst_all.py 3
mpirun -n 8 python biasvariance_vst_all.py 4
mpirun -n 8 python biasvariance_vst_all.py 5
mpirun -n 8 python biasvariance_vst_all.py 6
mpirun -n 8 python biasvariance_vst_all.py 7
mpirun -n 8 python biasvariance_vst_all.py 8
mpirun -n 8 python biasvariance_vst_all.py 9
mpirun -n 8 python biasvariance_vst_all.py 10
mpirun -n 8 python biasvariance_vst_all.py 11
mpirun -n 8 python biasvariance_vst_all.py 12
mpirun -n 8 python biasvariance_vst_all.py 13
mpirun -n 8 python biasvariance_vst_all.py 14
mpirun -n 8 python biasvariance_vst_all.py 15
mpirun -n 8 python biasvariance_vst_all.py 16
mpirun -n 8 python biasvariance_vst_all.py 17
mpirun -n 8 python biasvariance_vst_all.py 18
mpirun -n 8 python biasvariance_vst_all.py 19
mpirun -n 8 python biasvariance_vst_all.py 20
mpirun -n 8 python biasvariance_vst_all.py 21
mpirun -n 8 python biasvariance_vst_all.py 22
mpirun -n 8 python biasvariance_vst_all.py 23
mpirun -n 8 python biasvariance_vst_all.py 24
mpirun -n 8 python biasvariance_vst_all.py 25
mpirun -n 8 python biasvariance_vst_all.py 26
mpirun -n 8 python biasvariance_vst_all.py 27
mpirun -n 8 python biasvariance_vst_all.py 28
mpirun -n 8 python biasvariance_vst_all.py 29 
mpirun -n 8 python biasvariance_vst_all.py 30
mpirun -n 8 python biasvariance_vst_all.py 31
mpirun -n 8 python biasvariance_vst_all.py 32
mpirun -n 8 python biasvariance_vst_all.py 33
mpirun -n 8 python biasvariance_vst_all.py 34
