#!/bin/bash
mpirun -n 8 python decodingvt_cv_ilmerge.py 0 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 1 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 2 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 3 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 4 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 5 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 6 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 7 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 8 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 9 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 10 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 11 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 12 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 13 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 14 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 15 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 16 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 17 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 18 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 19 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 20 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 21 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 22 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 23 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 24 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 25 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 26 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 27 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 28 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 29 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 30 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 31 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 32 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 33 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_cv_ilmerge.py 34 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
