#!/bin/bash
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 0 2 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 0 2 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 0 6 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 0 6 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 0 9 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 0 9 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 1 2 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 1 2 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 1 6 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 1 6 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 1 9 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 1 9 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 2 2 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 2 2 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 2 6 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 2 6 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 2 9 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 2 9 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 3 2 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 3 2 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 3 6 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 3 6 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 3 9 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 3 9 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 4 2 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 4 2 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 4 6 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 4 6 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 4 9 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 4 9 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 5 2 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 5 2 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 5 6 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 5 6 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 5 9 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 5 9 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 6 2 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 6 2 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 6 6 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 6 6 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 6 9 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 6 9 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 7 2 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 7 2 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 7 6 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 7 6 M1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 7 9 S1
mpirun -n 8 python decodingvt_cv_ilmerge_cca.py 7 9 M1
