#!/bin/bash
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 0 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 1 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 2 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 3 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 4 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 5 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 6 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 7 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 8 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 9 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 10 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 11 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 12 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 13 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 14 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 15 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 16 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 17 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 18 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 19 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 20 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 21 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 22 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 23 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 24 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 25 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 26 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 27 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 28 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 29 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 30 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 31 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 32 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 33 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py trialized_windowed 34 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
