#!/bin/bash
mpirun -n 8 python decodingvt_residuals.py 0 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 1 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 2 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 3 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 4 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 5 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 6 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 7 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 8 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 9 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 10 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 11 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 12 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 13 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 14 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 15 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 16 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 17 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 18 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 19 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 20 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 21 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 22 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 23 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 24 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 25 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 26 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 27 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 28 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 29 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 30 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 31 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 32 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 33 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
mpirun -n 8 python decodingvt_residuals.py 34 0 --error_thresh=1.00 --error_op=le --q=0.00 --filter_op=le
