#!/bin/bash
mpirun -n 8 python decodingvt_cv_strvcorr.py 0
mpirun -n 8 python decodingvt_cv_strvcorr.py 1
mpirun -n 8 python decodingvt_cv_strvcorr.py 2
mpirun -n 8 python decodingvt_cv_strvcorr.py 3
mpirun -n 8 python decodingvt_cv_strvcorr.py 4
mpirun -n 8 python decodingvt_cv_strvcorr.py 5
mpirun -n 8 python decodingvt_cv_strvcorr.py 6
mpirun -n 8 python decodingvt_cv_strvcorr.py 7
mpirun -n 8 python decodingvt_cv_strvcorr.py 8
mpirun -n 8 python decodingvt_cv_strvcorr.py 9
mpirun -n 8 python decodingvt_cv_strvcorr.py 10
mpirun -n 8 python decodingvt_cv_strvcorr.py 11
mpirun -n 8 python decodingvt_cv_strvcorr.py 12
mpirun -n 8 python decodingvt_cv_strvcorr.py 13
mpirun -n 8 python decodingvt_cv_strvcorr.py 14
mpirun -n 8 python decodingvt_cv_strvcorr.py 15
mpirun -n 8 python decodingvt_cv_strvcorr.py 16
mpirun -n 8 python decodingvt_cv_strvcorr.py 17
mpirun -n 8 python decodingvt_cv_strvcorr.py 18
mpirun -n 8 python decodingvt_cv_strvcorr.py 19
mpirun -n 8 python decodingvt_cv_strvcorr.py 20
mpirun -n 8 python decodingvt_cv_strvcorr.py 21
mpirun -n 8 python decodingvt_cv_strvcorr.py 22
mpirun -n 8 python decodingvt_cv_strvcorr.py 23
mpirun -n 8 python decodingvt_cv_strvcorr.py 24
mpirun -n 8 python decodingvt_cv_strvcorr.py 25
mpirun -n 8 python decodingvt_cv_strvcorr.py 26
mpirun -n 8 python decodingvt_cv_strvcorr.py 27
mpirun -n 8 python decodingvt_cv_strvcorr.py 28
mpirun -n 8 python decodingvt_cv_strvcorr.py 29
mpirun -n 8 python decodingvt_cv_strvcorr.py 30
mpirun -n 8 python decodingvt_cv_strvcorr.py 31
mpirun -n 8 python decodingvt_cv_strvcorr.py 32
mpirun -n 8 python decodingvt_cv_strvcorr.py 33
mpirun -n 8 python decodingvt_cv_strvcorr.py 34
